packages:
  - packages/kanban
  - packages/kanban/web-ui
  - packages/merge
  - packages/tui
  - packages/vcs
  - packages/web-ui
  - packages/desktop
  - packages/docs

allowBuilds:
  esbuild: set this to true or false
