import { execFile as execFileCallback } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { promisify } from "node:util";

const execFile = promisify(execFileCallback);

type CommandOptions = {
	cwd?: string;
	allowFailure?: boolean;
};

type ScenarioName =
	| "baseline-stacks"
	| "dirty-workspace"
	| "workspace-conflict"
	| "commit-conflict"
	| "apply-stack-conflict"
	| "task-workspace-conflict";

type ScenarioDefinition = {
	name: ScenarioName;
	description: string;
	workspaceName: string;
	relativeWorkspacePath: string;
	revision: string;
	suggestedAppliedStacks: string[];
	expectedConflictPaths: string[];
	setup?: (paths: ScenarioPaths) => Promise<void>;
};

type ScenarioPaths = {
	rootPath: string;
	repoPath: string;
	workspacePath: string;
};

type ScenarioManifestEntry = {
	name: ScenarioName;
	description: string;
	repoPath: string;
	workspacePath: string;
	workspaceName: string;
	targetBranch: string;
	suggestedAppliedStacks: string[];
	expectedConflictPaths: string[];
	appUrl: string;
};

type ScenarioManifest = {
	rootPath: string;
	repoPath: string;
	remotePath: string;
	targetBranch: string;
	scenarios: ScenarioManifestEntry[];
};

type Options = {
	rootPath: string;
	scenarios: ScenarioName[];
	all: boolean;
	force: boolean;
	reset: boolean;
	json: boolean;
	list: boolean;
};

const USER_NAME = "VCS Scenario Fixture";
const USER_EMAIL = "vcs-scenarios@example.com";
const TARGET_BRANCH = "origin/main";
const DEFAULT_ROOT = "vcs-jj-scenarios";
const APP_BASE_URL = "http://localhost:3834";
const SCENARIO_README = [
	"# VCS JJ scenarios",
	"",
	"This repository is generated by `pnpm run vcs:jj-scenarios` from the ChangeYard checkout.",
	"It is intentionally deterministic and safe to delete or reset.",
	"",
	"## Recreate the fixture",
	"",
	"From the ChangeYard repository root:",
	"",
	"```sh",
	"pnpm run vcs:jj-scenarios -- --all --reset",
	"```",
	"",
	"Reset one scenario workspace:",
	"",
	"```sh",
	"pnpm run vcs:jj-scenarios -- --scenario workspace-conflict --reset",
	"```",
	"",
	"## Open in the app",
	"",
	"1. Add `vcs-jj-scenarios/repo` as a project.",
	"2. Expand the project workspaces in the VCS sidebar.",
	"3. Open the scenario workspace you want to test.",
	"4. Apply the suggested branch or inspect the listed conflict state.",
	"",
	"## Scenario guide",
	"",
	"| Scenario workspace | Suggested branch or stack | What to look for |",
	"| --- | --- | --- |",
	"| `baseline-stacks` | `feature/export-json`, `feature/cloud-observability` | Clean workspace with local, remote-only, and dependent stacks. Stack selection should show changed files without conflict styling. |",
	"| `dirty-workspace` | `feature/export-json` | Working copy has ordinary uncommitted edits. Applying the stack should keep the workspace usable and show normal file diffs. |",
	"| `workspace-conflict` | none | The current workspace is already conflicted. VCS should enter conflicted mode and show `src/conflict.rs` in the Working Copy conflict list. |",
	"| `commit-conflict` | `feature/commit-conflict` | Applying or viewing the stack should show a historical conflict commit for `src/conflict.rs`. The conflicted commit row should use conflict styling and show a warning icon. |",
	"| `apply-stack-conflict` | `feature/apply-conflict` | Start clean, then apply the stack. The workspace change should conflict with the stack in `src/apply.rs`. |",
	"| `task-workspace-conflict` | `feature/task-conflict-stack` | Task-style workspace path with a workspace-side edit. Applying the stack should surface a conflict in `src/task_flow.rs`. |",
	"",
	"## Useful JJ checks",
	"",
	"List workspaces:",
	"",
	"```sh",
	"jj workspace list",
	"```",
	"",
	"Check conflicts in the current workspace:",
	"",
	"```sh",
	"jj log -r 'conflicts() & ::@'",
	"jj resolve --list",
	"```",
	"",
	"Inspect the prepared conflict stack:",
	"",
	"```sh",
	"jj log -r '::feature/commit-conflict'",
	"```",
	"",
];

function usage(): string {
	return [
		"Usage: node --import tsx scripts/create-vcs-jj-scenarios.ts [root] [--scenario <name>] [--all] [--reset] [--force] [--json] [--list]",
		"",
		"Creates a persistent ignored JJ scenario fixture repo for VCS UI testing.",
		"",
		"Options:",
		"  --scenario <name>  Create or reset one named scenario workspace. Can be repeated.",
		"  --all              Create or reset every scenario workspace.",
		"  --reset            Recreate selected scenario workspaces from deterministic revisions.",
		"  --force            Rebuild the entire fixture root before creating scenarios.",
		"  --json             Print machine-readable manifest or scenario list.",
		"  --list             List available scenarios without creating the fixture.",
	].join("\n");
}

function isScenarioName(value: string): value is ScenarioName {
	return SCENARIOS.some((scenario) => scenario.name === value);
}

function parseArgs(argv: string[]): Options {
	let rootPath: string | null = null;
	let all = false;
	let force = false;
	let reset = false;
	let json = false;
	let list = false;
	const scenarios: ScenarioName[] = [];
	for (let index = 0; index < argv.length; index += 1) {
		const arg = argv[index];
		if (!arg || arg === "--") {
			continue;
		}
		if (arg === "--all") {
			all = true;
			continue;
		}
		if (arg === "--force") {
			force = true;
			continue;
		}
		if (arg === "--reset") {
			reset = true;
			continue;
		}
		if (arg === "--json") {
			json = true;
			continue;
		}
		if (arg === "--list") {
			list = true;
			continue;
		}
		if (arg === "--scenario") {
			const value = argv[index + 1];
			if (!value || !isScenarioName(value)) {
				throw new Error(`Unknown scenario: ${value ?? ""}`);
			}
			scenarios.push(value);
			index += 1;
			continue;
		}
		if (arg === "-h" || arg === "--help") {
			process.stdout.write(`${usage()}\n`);
			process.exit(0);
		}
		if (arg.startsWith("-")) {
			throw new Error(`Unknown option: ${arg}`);
		}
		if (rootPath) {
			throw new Error(`Unexpected extra root path: ${arg}`);
		}
		rootPath = arg;
	}
	return {
		rootPath: resolve(rootPath ?? DEFAULT_ROOT),
		scenarios: [...new Set(scenarios)],
		all,
		force,
		reset,
		json,
		list,
	};
}

async function run(command: string, args: string[], options: CommandOptions = {}): Promise<string> {
	const result = await execFile(command, args, {
		cwd: options.cwd,
		encoding: "utf8",
		maxBuffer: 20 * 1024 * 1024,
		env: {
			...process.env,
			GIT_AUTHOR_NAME: USER_NAME,
			GIT_AUTHOR_EMAIL: USER_EMAIL,
			GIT_COMMITTER_NAME: USER_NAME,
			GIT_COMMITTER_EMAIL: USER_EMAIL,
		},
	}).catch((error: Error & { stdout?: string; stderr?: string; code?: number }) => {
		if (options.allowFailure) {
			return { stdout: error.stdout ?? "", stderr: error.stderr ?? "" };
		}
		const details = [error.message, error.stdout, error.stderr].filter(Boolean).join("\n");
		throw new Error(`${command} ${args.join(" ")} failed\n${details}`);
	});
	return result.stdout.trim();
}

async function jj(cwd: string, args: string[], options: CommandOptions = {}): Promise<string> {
	return await run(
		"jj",
		[
			"--no-pager",
			"--config",
			`user.name=${JSON.stringify(USER_NAME)}`,
			"--config",
			`user.email=${JSON.stringify(USER_EMAIL)}`,
			"--config",
			"signing.behavior='drop'",
			...args,
		],
		{ ...options, cwd },
	);
}

async function writeRepoFile(root: string, relativePath: string, content: string): Promise<void> {
	const filePath = resolve(root, relativePath);
	await mkdir(dirname(filePath), { recursive: true });
	await writeFile(filePath, content);
}

async function applyFiles(root: string, files: Record<string, string>): Promise<void> {
	for (const [relativePath, content] of Object.entries(files)) {
		await writeRepoFile(root, relativePath, content);
	}
}

async function createCommit(repoPath: string, input: {
	parent: string;
	message: string;
	files: Record<string, string>;
	bookmark?: string;
}): Promise<void> {
	await jj(repoPath, ["new", input.parent, "-m", input.message]);
	await applyFiles(repoPath, input.files);
	await jj(repoPath, ["commit", "-m", input.message]);
	if (input.bookmark) {
		await jj(repoPath, ["bookmark", "set", input.bookmark, "-r", "@-"]);
	}
}

async function createConflictBookmark(repoPath: string, input: {
	parents: [string, string];
	message: string;
	bookmark: string;
}): Promise<void> {
	await jj(repoPath, ["new", ...input.parents, "-m", input.message]);
	await jj(repoPath, ["bookmark", "set", input.bookmark, "-r", "@"]);
	await jj(repoPath, ["new", "main", "-m", "scenario repo parking"]);
}

async function buildBaseRepository(rootPath: string, force: boolean): Promise<{ repoPath: string; remotePath: string }> {
	const repoPath = join(rootPath, "repo");
	const remotePath = join(rootPath, "remote.git");
	if (force) {
		await rm(rootPath, { recursive: true, force: true });
	}
	await mkdir(rootPath, { recursive: true });
	await mkdir(dirname(repoPath), { recursive: true });
	await run("git", ["init", "--bare", remotePath]);
	await jj(process.cwd(), ["git", "init", "--colocate", repoPath]);
	await jj(repoPath, ["git", "remote", "add", "origin", remotePath]);

	await applyFiles(repoPath, {
		".gitignore": ["target/", "node_modules/", ".DS_Store", "*.log", ".changeyard/workspaces/", ""].join("\n"),
		".changeyard/config.local.jsonc": JSON.stringify(
			{
				provider: { type: "noop" },
				vcs: { engine: "jj", fallback: "jj", targetBranch: TARGET_BRANCH },
				project: { defaultBase: "main" },
			},
			null,
			2,
		),
		"README.md": SCENARIO_README.join("\n"),
		"src/tasks.rs": [
			"pub struct Task {",
			"    pub id: u64,",
			"    pub title: String,",
			"}",
			"",
		].join("\n"),
		"src/conflict.rs": [
			"pub fn conflict_label() -> &'static str {",
			"    \"base\"",
			"}",
			"",
		].join("\n"),
		"src/apply.rs": [
			"pub fn apply_label() -> &'static str {",
			"    \"base\"",
			"}",
			"",
		].join("\n"),
		"src/task_flow.rs": [
			"pub fn task_label() -> &'static str {",
			"    \"base\"",
			"}",
			"",
		].join("\n"),
	});
	await jj(repoPath, ["commit", "-m", "initial scenario repository"]);
	await jj(repoPath, ["bookmark", "set", "main", "-r", "@-"]);

	await createCommit(repoPath, {
		parent: "main",
		message: "document scenario fixture",
		files: {
			"README.md": SCENARIO_README.join("\n"),
		},
		bookmark: "main",
	});

	await createCommit(repoPath, {
		parent: "main",
		message: "add json report mode",
		files: {
			"src/output.rs": [
				"use crate::tasks::Task;",
				"",
				"pub fn render_json(tasks: &[Task]) -> String {",
				"    format!(\"{} tasks\", tasks.len())",
				"}",
				"",
			].join("\n"),
		},
	});
	await createCommit(repoPath, {
		parent: "@-",
		message: "add serde task serialization",
		files: {
			"Cargo.toml": [
				"[package]",
				"name = \"vcs-jj-scenarios\"",
				"version = \"0.1.0\"",
				"edition = \"2021\"",
				"",
				"[dependencies]",
				"serde = { version = \"1\", features = [\"derive\"] }",
				"",
			].join("\n"),
			"src/tasks.rs": [
				"use serde::{Deserialize, Serialize};",
				"",
				"#[derive(Clone, Debug, Deserialize, Serialize)]",
				"pub struct Task {",
				"    pub id: u64,",
				"    pub title: String,",
				"    pub completed: bool,",
				"}",
				"",
			].join("\n"),
		},
		bookmark: "feature/export-json",
	});

	await createCommit(repoPath, {
		parent: "main",
		message: "prepare cloud deployment config",
		files: {
			"deploy/cloud.toml": ["[service]", "name = \"task-tracker\"", "region = \"test\"", ""].join("\n"),
		},
	});
	await createCommit(repoPath, {
		parent: "@-",
		message: "add deployment preview command",
		files: {
			"src/cloud.rs": [
				"pub fn preview_deployment() -> &'static str {",
				"    \"deployment preview\"",
				"}",
				"",
			].join("\n"),
		},
		bookmark: "feature/cloud-runner",
	});
	await createCommit(repoPath, {
		parent: "feature/cloud-runner",
		message: "add deployment health summary",
		files: {
			"src/cloud.rs": [
				"pub fn preview_deployment() -> &'static str {",
				"    \"deployment preview\"",
				"}",
				"",
				"pub fn health_summary() -> &'static str {",
				"    \"healthy\"",
				"}",
				"",
			].join("\n"),
		},
		bookmark: "feature/cloud-observability",
	});

	await createCommit(repoPath, {
		parent: "main",
		message: "polish readme usage notes",
		files: {
			"README.md": "# VCS JJ scenarios\n\nRemote-only usage notes for testing branch inventory.\n",
		},
		bookmark: "feature/readme-polish",
	});
	await jj(repoPath, ["git", "push", "--remote", "origin", "--all"]);
	await jj(repoPath, ["bookmark", "forget", "feature/readme-polish"]);
	await jj(repoPath, ["git", "fetch", "--remote", "origin"]);

	await createCommit(repoPath, {
		parent: "main",
		message: "left conflict variant",
		files: {
			"src/conflict.rs": ["pub fn conflict_label() -> &'static str {", "    \"left\"", "}", ""].join("\n"),
		},
		bookmark: "feature/conflict-left",
	});
	await createCommit(repoPath, {
		parent: "main",
		message: "right conflict variant",
		files: {
			"src/conflict.rs": ["pub fn conflict_label() -> &'static str {", "    \"right\"", "}", ""].join("\n"),
		},
		bookmark: "feature/conflict-right",
	});
	await createConflictBookmark(repoPath, {
		parents: ["feature/conflict-left", "feature/conflict-right"],
		message: "commit conflict merge",
		bookmark: "feature/commit-conflict",
	});

	await createCommit(repoPath, {
		parent: "main",
		message: "stack side apply conflict",
		files: {
			"src/apply.rs": ["pub fn apply_label() -> &'static str {", "    \"stack\"", "}", ""].join("\n"),
		},
		bookmark: "feature/apply-conflict",
	});
	await createCommit(repoPath, {
		parent: "main",
		message: "task side conflict stack",
		files: {
			"src/task_flow.rs": ["pub fn task_label() -> &'static str {", "    \"stack\"", "}", ""].join("\n"),
		},
		bookmark: "feature/task-conflict-stack",
	});

	await jj(repoPath, ["new", "main", "-m", "scenario repo parking"]);
	return { repoPath, remotePath };
}

const SCENARIOS: ScenarioDefinition[] = [
	{
		name: "baseline-stacks",
		description: "Clean workspace with several local, remote-only, and dependent stacks.",
		workspaceName: "scenario-baseline-stacks",
		relativeWorkspacePath: "workspaces/baseline-stacks",
		revision: "main",
		suggestedAppliedStacks: ["feature/export-json", "feature/cloud-observability"],
		expectedConflictPaths: [],
	},
	{
		name: "dirty-workspace",
		description: "Workspace with ordinary working-copy changes and a suggested stack.",
		workspaceName: "scenario-dirty-workspace",
		relativeWorkspacePath: "workspaces/dirty-workspace",
		revision: "main",
		suggestedAppliedStacks: ["feature/export-json"],
		expectedConflictPaths: [],
		setup: async ({ workspacePath }) => {
			await writeRepoFile(
				workspacePath,
				"notes/dirty-workspace.md",
				"# Dirty workspace\n\nThis uncommitted file is present so the VCS UI has a normal working-copy edit to render.\n",
			);
		},
	},
	{
		name: "workspace-conflict",
		description: "Current workspace change is a real JJ merge conflict.",
		workspaceName: "scenario-workspace-conflict",
		relativeWorkspacePath: "workspaces/workspace-conflict",
		revision: "main",
		suggestedAppliedStacks: [],
		expectedConflictPaths: ["src/conflict.rs"],
		setup: async ({ workspacePath }) => {
			await jj(workspacePath, ["new", "feature/conflict-left", "feature/conflict-right", "-m", "workspace conflict merge"]);
		},
	},
	{
		name: "commit-conflict",
		description: "Clean workspace that can apply a stack containing a historical conflict commit.",
		workspaceName: "scenario-commit-conflict",
		relativeWorkspacePath: "workspaces/commit-conflict",
		revision: "main",
		suggestedAppliedStacks: ["feature/commit-conflict"],
		expectedConflictPaths: ["src/conflict.rs"],
	},
	{
		name: "apply-stack-conflict",
		description: "Applying feature/apply-conflict rebases the workspace change into a conflict.",
		workspaceName: "scenario-apply-stack-conflict",
		relativeWorkspacePath: "workspaces/apply-stack-conflict",
		revision: "main",
		suggestedAppliedStacks: ["feature/apply-conflict"],
		expectedConflictPaths: ["src/apply.rs"],
		setup: async ({ workspacePath }) => {
			await writeRepoFile(
				workspacePath,
				"src/apply.rs",
				["pub fn apply_label() -> &'static str {", "    \"workspace\"", "}", ""].join("\n"),
			);
			await jj(workspacePath, ["describe", "-m", "workspace side apply conflict"]);
		},
	},
	{
		name: "task-workspace-conflict",
		description: "Task-style workspace path whose current change conflicts after applying a task stack.",
		workspaceName: "cy-CY-CONFLICT",
		relativeWorkspacePath: "repo/.changeyard/workspaces/CY-CONFLICT/repo",
		revision: "main",
		suggestedAppliedStacks: ["feature/task-conflict-stack"],
		expectedConflictPaths: ["src/task_flow.rs"],
		setup: async ({ workspacePath }) => {
			await writeRepoFile(
				workspacePath,
				"src/task_flow.rs",
				["pub fn task_label() -> &'static str {", "    \"workspace\"", "}", ""].join("\n"),
			);
			await jj(workspacePath, ["describe", "-m", "CY-CONFLICT: workspace side task conflict"]);
		},
	},
];

function scenarioByName(name: ScenarioName): ScenarioDefinition {
	const scenario = SCENARIOS.find((candidate) => candidate.name === name);
	if (!scenario) {
		throw new Error(`Unknown scenario: ${name}`);
	}
	return scenario;
}

function selectedScenarios(options: Options): ScenarioDefinition[] {
	if (options.all || options.scenarios.length === 0) {
		return SCENARIOS;
	}
	return options.scenarios.map(scenarioByName);
}

async function forgetWorkspace(repoPath: string, workspaceName: string): Promise<void> {
	await jj(repoPath, ["workspace", "forget", workspaceName], { allowFailure: true });
}

async function createScenarioWorkspace(rootPath: string, repoPath: string, scenario: ScenarioDefinition, reset: boolean): Promise<ScenarioManifestEntry> {
	const workspacePath = resolve(rootPath, scenario.relativeWorkspacePath);
	if (reset) {
		await forgetWorkspace(repoPath, scenario.workspaceName);
		await rm(workspacePath, { recursive: true, force: true });
	}
	await mkdir(dirname(workspacePath), { recursive: true });
	await jj(repoPath, [
		"workspace",
		"add",
		"--name",
		scenario.workspaceName,
		"-r",
		scenario.revision,
		"-m",
		scenario.description,
		workspacePath,
	]);
	await scenario.setup?.({ rootPath, repoPath, workspacePath });
	return {
		name: scenario.name,
		description: scenario.description,
		repoPath,
		workspacePath,
		workspaceName: scenario.workspaceName,
		targetBranch: TARGET_BRANCH,
		suggestedAppliedStacks: scenario.suggestedAppliedStacks,
		expectedConflictPaths: scenario.expectedConflictPaths,
		appUrl: `${APP_BASE_URL}/vcs?workspaceId=${encodeURIComponent(scenario.workspaceName)}`,
	};
}

async function readExistingManifest(rootPath: string): Promise<ScenarioManifest | null> {
	try {
		return JSON.parse(await readFile(join(rootPath, "manifest.json"), "utf8")) as ScenarioManifest;
	} catch {
		return null;
	}
}

async function writeManifest(manifest: ScenarioManifest): Promise<void> {
	await writeFile(join(manifest.rootPath, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
}

async function createScenarios(options: Options): Promise<ScenarioManifest> {
	const repoPath = join(options.rootPath, "repo");
	const existing = await readExistingManifest(options.rootPath);
	const shouldBuildBase = options.force || !existing;
	const base = shouldBuildBase
		? await buildBaseRepository(options.rootPath, options.force)
		: { repoPath, remotePath: join(options.rootPath, "remote.git") };
	const scenariosToCreate = selectedScenarios(options);
	const resetWorkspaces = options.reset || shouldBuildBase;
	const nextEntriesByName = new Map<ScenarioName, ScenarioManifestEntry>(
		(existing?.scenarios ?? []).map((scenario) => [scenario.name, scenario]),
	);
	for (const scenario of scenariosToCreate) {
		if (!resetWorkspaces && nextEntriesByName.has(scenario.name)) {
			continue;
		}
		nextEntriesByName.set(scenario.name, await createScenarioWorkspace(options.rootPath, base.repoPath, scenario, resetWorkspaces));
	}
	const manifest: ScenarioManifest = {
		rootPath: options.rootPath,
		repoPath: base.repoPath,
		remotePath: base.remotePath,
		targetBranch: TARGET_BRANCH,
		scenarios: SCENARIOS.map((scenario) => nextEntriesByName.get(scenario.name)).filter((entry): entry is ScenarioManifestEntry => Boolean(entry)),
	};
	await writeManifest(manifest);
	return manifest;
}

function listScenarios(json: boolean): void {
	const available = SCENARIOS.map(({ name, description, suggestedAppliedStacks, expectedConflictPaths }) => ({
		name,
		description,
		suggestedAppliedStacks,
		expectedConflictPaths,
	}));
	if (json) {
		process.stdout.write(`${JSON.stringify({ scenarios: available }, null, 2)}\n`);
		return;
	}
	for (const scenario of available) {
		process.stdout.write(`${scenario.name}\n  ${scenario.description}\n`);
	}
}

try {
	const options = parseArgs(process.argv.slice(2));
	if (options.list) {
		listScenarios(options.json);
		process.exit(0);
	}
	const manifest = await createScenarios(options);
	if (options.json) {
		process.stdout.write(`${JSON.stringify(manifest, null, 2)}\n`);
	} else {
		process.stdout.write(`Created JJ scenario fixture at ${manifest.rootPath}\n`);
		process.stdout.write(`Project repo: ${manifest.repoPath}\n`);
		process.stdout.write(`Manifest: ${join(manifest.rootPath, "manifest.json")}\n`);
		for (const scenario of manifest.scenarios) {
			process.stdout.write(`- ${scenario.name}: ${scenario.workspacePath}\n`);
		}
	}
} catch (error) {
	const message = error instanceof Error ? error.message : String(error);
	process.stderr.write(`${message}\n\n${usage()}\n`);
	process.exit(1);
}
